# Generated by Django 6.0.7 on 2026-07-23 02:24

import django.core.validators
import django.db.models.deletion
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('port_count', models.PositiveIntegerField()),
                ('port_type', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('port_count', models.PositiveIntegerField()),
                ('port_type', models.CharField(help_text='e.g. "8x 1GbE Copper + 2x 1GbE Combo".', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('slot_count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('rack_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('dhcp_server_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switches', to='inventory.networkswitchtype')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='switches', to='inventory.rack')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('rack_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.networkdevicetype')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.rack')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('vlan_id', models.PositiveIntegerField(help_text='802.1Q VLAN ID (1-4094).', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('subnet', models.CharField(help_text='IPv4 subnet in CIDR notation, e.g. 10.200.0.0/21.', max_length=18, validators=[inventory.validators.validate_ipv4_cidr])),
                ('default_gateway', models.GenericIPAddressField(blank=True, help_text='Suggested as the lowest host address in the subnet; stored and overridable.', null=True, protocol='IPv4')),
                ('dhcp_range', models.CharField(blank=True, help_text='Suggested as the bottom /24 of the subnet; stored and overridable.', max_length=18, validators=[inventory.validators.validate_ipv4_cidr])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vlan_id'],
            },
        ),
        migrations.CreateModel(
            name='RackVlanRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address_range', models.CharField(max_length=18, validators=[inventory.validators.validate_ipv4_cidr])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_ranges', to='inventory.rack')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rack_ranges', to='inventory.vlan')),
            ],
            options={
                'ordering': ['vlan', 'address_range'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('port_type', models.CharField(blank=True, help_text='e.g. 1GbE, 10GbE SFP+.', max_length=50)),
                ('port_mode', models.CharField(choices=[('trunk', 'Trunk'), ('access', 'Access')], default='access', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.networkswitch')),
                ('allowed_vlans', models.ManyToManyField(blank=True, related_name='+', to='inventory.vlan')),
                ('native_vlan', models.ForeignKey(blank=True, help_text='Primary (untagged) VLAN for this port.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlan')),
            ],
            options={
                'ordering': ['switch', 'port_number'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='inventory.networkswitch')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switch_addresses', to='inventory.vlan')),
            ],
            options={
                'ordering': ['vlan', 'address'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevicePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_dhcp', models.BooleanField(default=False)),
                ('address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('default_gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.networkdevice')),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_device_ports', to='inventory.networkswitch')),
                ('switch_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_device_ports', to='inventory.networkswitchport')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_ports', to='inventory.vlan')),
            ],
            options={
                'ordering': ['device', 'vlan'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkdevicetype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model'), name='unique_device_type'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchtype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model'), name='unique_switch_type'),
        ),
        migrations.AddConstraint(
            model_name='networkswitch',
            constraint=models.UniqueConstraint(fields=('rack', 'rack_slot'), name='unique_switch_rack_slot'),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.UniqueConstraint(fields=('rack', 'rack_slot'), name='unique_device_rack_slot'),
        ),
        migrations.AddConstraint(
            model_name='rackvlanrange',
            constraint=models.UniqueConstraint(fields=('rack', 'vlan'), name='unique_rack_vlan_range'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchport',
            constraint=models.UniqueConstraint(fields=('switch', 'port_number'), name='unique_switch_port_number'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchaddress',
            constraint=models.UniqueConstraint(fields=('switch', 'vlan'), name='unique_switch_vlan_address'),
        ),
    ]
