# Generated by Django 6.0.7 on 2026-07-23 16:50

import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkswitchaddress',
            name='address',
            field=models.GenericIPAddressField(blank=True, help_text='Leave blank to suggest rack range base + rack slot.', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='rackvlanrange',
            name='address_range',
            field=models.CharField(blank=True, help_text="Leave blank to suggest the next free block sized for the rack's slot_count.", max_length=18, validators=[inventory.validators.validate_ipv4_cidr]),
        ),
        migrations.AddConstraint(
            model_name='networkswitchaddress',
            constraint=models.CheckConstraint(condition=models.Q(('address__isnull', False)), name='networkswitchaddress_address_required'),
        ),
    ]
