# Generated by Django 6.0.7 on 2026-07-23 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_networkswitchaddress_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='networkdeviceport',
            constraint=models.UniqueConstraint(fields=('vlan', 'address'), name='unique_device_port_vlan_address_value'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchaddress',
            constraint=models.UniqueConstraint(fields=('vlan', 'address'), name='unique_switch_vlan_address_value'),
        ),
    ]
