# Generated by Django 6.0.7 on 2026-07-24 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_networkdeviceport_unique_device_port_vlan_address_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDeviceTypePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(help_text='Required — this port\'s purpose/identity, e.g. "Dante Primary".', max_length=255)),
                ('port_type', models.CharField(choices=[('10_100m_rj45', '10/100M RJ45'), ('1gbe_rj45', '1GbE RJ45 (copper)'), ('1gbe_sfp', '1GbE SFP'), ('1gbe_combo', '1GbE Combo (RJ45/SFP)'), ('2_5gbe_rj45', '2.5GbE RJ45'), ('10gbe_rj45', '10GbE RJ45'), ('10gbe_sfp_plus', '10GbE SFP+'), ('25gbe_sfp28', '25GbE SFP28'), ('other', 'Other / Unknown')], max_length=20)),
                ('ordinal', models.PositiveIntegerField(default=0, editable=False, help_text='Stable display order; auto-assigned.')),
            ],
            options={
                'ordering': ['device_type', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitchPortAllowedVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSwitchTypePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('port_type', models.CharField(choices=[('10_100m_rj45', '10/100M RJ45'), ('1gbe_rj45', '1GbE RJ45 (copper)'), ('1gbe_sfp', '1GbE SFP'), ('1gbe_combo', '1GbE Combo (RJ45/SFP)'), ('2_5gbe_rj45', '2.5GbE RJ45'), ('10gbe_rj45', '10GbE RJ45'), ('10gbe_sfp_plus', '10GbE SFP+'), ('25gbe_sfp28', '25GbE SFP28'), ('other', 'Other / Unknown')], max_length=20)),
                ('port_mode', models.CharField(choices=[('trunk', 'Trunk'), ('access', 'Access')], default='access', max_length=10)),
            ],
            options={
                'ordering': ['switch_type', 'port_number'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitchTypePortAllowedVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='networkdeviceport',
            options={'ordering': ['device', 'ordinal']},
        ),
        migrations.AlterModelOptions(
            name='networkdevicetype',
            options={'ordering': ['manufacturer', 'model', 'name']},
        ),
        migrations.AlterModelOptions(
            name='networkswitchtype',
            options={'ordering': ['manufacturer', 'model', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='networkdeviceport',
            name='unique_device_port_number',
        ),
        migrations.RemoveConstraint(
            model_name='networkdeviceport',
            name='device_port_dhcp_xor_static_address',
        ),
        migrations.RemoveConstraint(
            model_name='networkdevicetype',
            name='unique_device_type',
        ),
        migrations.RemoveConstraint(
            model_name='networkswitchtype',
            name='unique_switch_type',
        ),
        migrations.AddField(
            model_name='networkdeviceport',
            name='ordinal',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='networkdeviceport',
            name='port_type',
            field=models.CharField(blank=True, choices=[('10_100m_rj45', '10/100M RJ45'), ('1gbe_rj45', '1GbE RJ45 (copper)'), ('1gbe_sfp', '1GbE SFP'), ('1gbe_combo', '1GbE Combo (RJ45/SFP)'), ('2_5gbe_rj45', '2.5GbE RJ45'), ('10gbe_rj45', '10GbE RJ45'), ('10gbe_sfp_plus', '10GbE SFP+'), ('25gbe_sfp28', '25GbE SFP28'), ('other', 'Other / Unknown')], help_text="Physical hardware fact, copied from the device's type — locked after creation.", max_length=20),
        ),
        migrations.AddField(
            model_name='networkdevicetype',
            name='name',
            field=models.CharField(default='Default', help_text='Profile label, e.g. "with Dante Card", or "Default" for a single-profile model.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkswitchtype',
            name='name',
            field=models.CharField(default='Default', help_text='Profile label, e.g. "For Drive Rack", or "Default" for a single-profile model.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkdeviceport',
            name='description',
            field=models.CharField(help_text='Required — this port\'s purpose, e.g. "Dante Primary".', max_length=255),
        ),
        migrations.AlterField(
            model_name='networkdeviceport',
            name='port_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='networkdevicetype',
            name='port_count',
            field=models.PositiveIntegerField(help_text='Must equal the number of Network Device Type Ports defined for this profile.'),
        ),
        migrations.AlterField(
            model_name='networkswitchport',
            name='port_type',
            field=models.CharField(blank=True, choices=[('10_100m_rj45', '10/100M RJ45'), ('1gbe_rj45', '1GbE RJ45 (copper)'), ('1gbe_sfp', '1GbE SFP'), ('1gbe_combo', '1GbE Combo (RJ45/SFP)'), ('2_5gbe_rj45', '2.5GbE RJ45'), ('10gbe_rj45', '10GbE RJ45'), ('10gbe_sfp_plus', '10GbE SFP+'), ('25gbe_sfp28', '25GbE SFP28'), ('other', 'Other / Unknown')], help_text="Physical hardware fact, copied from the switch's type — locked after creation.", max_length=20),
        ),
        migrations.AlterField(
            model_name='networkswitchtype',
            name='port_count',
            field=models.PositiveIntegerField(help_text='Must equal the number of Network Switch Type Ports defined for this profile.'),
        ),
        migrations.AddConstraint(
            model_name='networkdevicetype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model', 'name'), name='unique_device_type'),
        ),
        migrations.AddConstraint(
            model_name='networkdevicetype',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='networkdevicetype_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchtype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model', 'name'), name='unique_switch_type'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchtype',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='networkswitchtype_name_not_blank'),
        ),
        migrations.AddField(
            model_name='networkdevicetypeport',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkdevicetypeport',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_ports', to='inventory.networkdevicetype'),
        ),
        migrations.AddField(
            model_name='networkdevicetypeport',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlan'),
        ),
        migrations.AddField(
            model_name='networkdeviceport',
            name='source_type_port',
            field=models.ForeignKey(blank=True, editable=False, help_text="Provenance only — never used to re-derive this port's fields (seed-once).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_ports', to='inventory.networkdevicetypeport'),
        ),
        migrations.AddConstraint(
            model_name='networkdeviceport',
            constraint=models.UniqueConstraint(fields=('device', 'description'), name='unique_device_port_description'),
        ),
        migrations.AddConstraint(
            model_name='networkdeviceport',
            constraint=models.UniqueConstraint(fields=('device', 'ordinal'), name='unique_device_port_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='networkdeviceport',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='networkdeviceport_description_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='networkdeviceport',
            constraint=models.CheckConstraint(condition=models.Q(('port_number__isnull', True), ('port_number__gte', 1), _connector='OR'), name='networkdeviceport_port_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='networkdeviceport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address__isnull', True), ('is_dhcp', True)), models.Q(('address__isnull', False), ('is_dhcp', False)), _connector='OR'), name='device_port_dhcp_xor_static_address'),
        ),
        migrations.AddField(
            model_name='networkswitchportallowedvlan',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkswitchportallowedvlan',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_vlan_links', to='inventory.networkswitchport'),
        ),
        migrations.AddField(
            model_name='networkswitchportallowedvlan',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlan'),
        ),
        # Django can't AlterField an M2M into a custom-through M2M in one
        # step ("cannot alter to or from M2M fields, or add or remove
        # through= on M2M fields") — drop the old plain-M2M column and
        # re-add it pointing at the new through model instead.
        migrations.RemoveField(
            model_name='networkswitchport',
            name='allowed_vlans',
        ),
        migrations.AddField(
            model_name='networkswitchport',
            name='allowed_vlans',
            field=models.ManyToManyField(blank=True, related_name='+', through='inventory.NetworkSwitchPortAllowedVlan', to='inventory.vlan'),
        ),
        migrations.AddField(
            model_name='networkswitchtypeport',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkswitchtypeport',
            name='native_vlan',
            field=models.ForeignKey(blank=True, help_text='Primary (untagged) VLAN for this port.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlan'),
        ),
        migrations.AddField(
            model_name='networkswitchtypeport',
            name='switch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_ports', to='inventory.networkswitchtype'),
        ),
        migrations.AddField(
            model_name='networkswitchport',
            name='source_type_port',
            field=models.ForeignKey(blank=True, editable=False, help_text="Provenance only — never used to re-derive this port's fields (seed-once).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_ports', to='inventory.networkswitchtypeport'),
        ),
        migrations.AddField(
            model_name='networkswitchtypeportallowedvlan',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkswitchtypeportallowedvlan',
            name='type_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_vlan_links', to='inventory.networkswitchtypeport'),
        ),
        migrations.AddField(
            model_name='networkswitchtypeportallowedvlan',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlan'),
        ),
        migrations.AddField(
            model_name='networkswitchtypeport',
            name='allowed_vlans',
            field=models.ManyToManyField(blank=True, related_name='+', through='inventory.NetworkSwitchTypePortAllowedVlan', to='inventory.vlan'),
        ),
        migrations.RemoveField(
            model_name='networkdeviceport',
            name='default_gateway',
        ),
        migrations.RemoveField(
            model_name='networkdevicetype',
            name='port_type',
        ),
        migrations.RemoveField(
            model_name='networkswitchtype',
            name='port_type',
        ),
        migrations.AddConstraint(
            model_name='networkdevicetypeport',
            constraint=models.UniqueConstraint(fields=('device_type', 'description'), name='unique_device_type_port_description'),
        ),
        migrations.AddConstraint(
            model_name='networkdevicetypeport',
            constraint=models.UniqueConstraint(fields=('device_type', 'ordinal'), name='unique_device_type_port_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='networkdevicetypeport',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='networkdevicetypeport_description_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='networkdevicetypeport',
            constraint=models.CheckConstraint(condition=models.Q(('port_number__isnull', True), ('port_number__gte', 1), _connector='OR'), name='networkdevicetypeport_port_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchportallowedvlan',
            constraint=models.UniqueConstraint(fields=('port', 'vlan'), name='unique_switch_port_allowed_vlan'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchtypeportallowedvlan',
            constraint=models.UniqueConstraint(fields=('type_port', 'vlan'), name='unique_switch_type_port_allowed_vlan'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchtypeport',
            constraint=models.UniqueConstraint(fields=('switch_type', 'port_number'), name='unique_switch_type_port_number'),
        ),
        migrations.AddConstraint(
            model_name='networkswitchtypeport',
            constraint=models.CheckConstraint(condition=models.Q(('port_number__gte', 1)), name='networkswitchtypeport_port_number_gte_1'),
        ),
    ]
