# Generated by Django 6.0.7 on 2026-07-26 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_networkdevicetypeport_networkswitchportallowedvlan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='dhcp_range',
        ),
        migrations.AddField(
            model_name='vlan',
            name='dhcp_range_end',
            field=models.GenericIPAddressField(blank=True, help_text='End of the DHCP address range (inclusive). Must be greater than the start address.', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='dhcp_range_start',
            field=models.GenericIPAddressField(blank=True, help_text='Start of the DHCP address range (inclusive). Leave both start and end blank if this VLAN has no DHCP range.', null=True, protocol='IPv4'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dhcp_range_end__isnull', True), ('dhcp_range_start__isnull', True)), models.Q(('dhcp_range_end__isnull', False), ('dhcp_range_start__isnull', False)), _connector='OR'), name='vlan_dhcp_range_start_end_together'),
        ),
    ]
