# Generated by Django 6.0.7 on 2026-07-26 13:19, then hand-edited — see
# ADR 0012 and PLAN-switch-port-vlan-profiles.md.
#
# Destructive, same posture as ADR 0010's own migration: this project's local
# databases are rebuilt, not migrated over, so there is no attempt to
# translate existing per-port port_mode/native_vlan/allowed_vlans into
# generated profiles. Every NetworkSwitchTypePort/NetworkSwitchPort ends up
# pointing at the seeded "Default" profile instead — a destructive default
# assignment, not a no-op. If real production data ever exists before this
# runs, a staged backfill must be written first (same caveat ADR 0010 makes).

import django.db.models.deletion
import inventory.models
import inventory.validators
from django.conf import settings
from django.db import migrations, models
from inventory.models import DEFAULT_PROFILE_NAME, DEFAULT_VLAN_ID, DEFAULT_VLAN_NAME


def seed_defaults(apps, schema_editor):
    """Seed the system Default VLAN (id 1, no subnet — ADR 0012's
    representation of 802.1Q VLAN 1) and the system Default Switch Port
    VLAN Profile — the fallback every unselected ``NetworkSwitchTypePort``
    lands on (DESIGN.md's "Switch Port Profile VLAN Selection").

    Fails loudly on a conflicting pre-existing row rather than silently
    adopting it: this project's databases are rebuilt, not migrated over
    (ADR 0010), so a mismatched existing row means something is already
    wrong, and quietly adopting it would produce a "Default" that isn't
    actually the documented default. Uses ``get_or_create`` (not a bare
    ``create``) only so this migration is safe to re-run against a database
    where it partially applied before.

    Reverse is a documented no-op (see this migration's ``RunPython`` call)
    — ``get_or_create``'s ``created`` flag isn't available at reversal
    time, so a reverse function has no way to tell a row it created here
    from one that already existed, and deleting a pre-existing VLAN 1 on
    rollback would be worse than leaving both rows in place.
    """
    VLAN = apps.get_model("inventory", "VLAN")
    SwitchPortVlanProfile = apps.get_model("inventory", "SwitchPortVlanProfile")

    vlan, vlan_created = VLAN.objects.get_or_create(
        vlan_id=DEFAULT_VLAN_ID,
        defaults={"name": DEFAULT_VLAN_NAME, "subnet": ""},
    )
    if not vlan_created and (vlan.name != DEFAULT_VLAN_NAME or vlan.subnet != ""):
        raise RuntimeError(
            f"VLAN id={DEFAULT_VLAN_ID} already exists as {vlan.name!r} (subnet={vlan.subnet!r}), "
            f"but this migration expects to seed it as {DEFAULT_VLAN_NAME!r} with no subnet. "
            "This project's databases are rebuilt, not migrated over (ADR 0010) — resolve or "
            "remove the conflicting row before migrating."
        )

    # Keyed on ``is_system``, not ``name`` — the system profile's name is
    # deliberately editable (ADR 0012), so name is not a stable identity for
    # it. See the matching note in the seed_defaults management command.
    profile = SwitchPortVlanProfile.objects.filter(is_system=True).first()
    if profile is None:
        if SwitchPortVlanProfile.objects.filter(name=DEFAULT_PROFILE_NAME).exists():
            raise RuntimeError(
                f"No system Switch Port VLAN Profile exists, but an ordinary profile is already "
                f"named {DEFAULT_PROFILE_NAME!r} (``name`` is unique). This project's databases "
                "are rebuilt, not migrated over (ADR 0010) — resolve or remove the conflicting "
                "row before migrating."
            )
        SwitchPortVlanProfile.objects.create(
            name=DEFAULT_PROFILE_NAME,
            port_mode="trunk",
            native_vlan=vlan,
            all_vlans_allowed=True,
            is_system=True,
        )
    elif (
        profile.native_vlan_id != vlan.pk
        or profile.port_mode != "trunk"
        or not profile.all_vlans_allowed
    ):
        raise RuntimeError(
            f"A system Switch Port VLAN Profile ({profile.name!r}) already exists but doesn't "
            "match this migration's expected values (native_vlan=Default VLAN, port_mode=trunk, "
            "all_vlans_allowed=True). This project's databases are rebuilt, not migrated over "
            "(ADR 0010) — resolve or remove the conflicting row before migrating."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_vlan_dhcp_range_vlan_dhcp_range_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchPortVlanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "port_mode",
                    models.CharField(
                        choices=[("trunk", "Trunk"), ("access", "Access")],
                        default="trunk",
                        help_text="Defaults to Trunk (DESIGN.md).",
                        max_length=10,
                    ),
                ),
                (
                    "all_vlans_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="If set, every VLAN is allowed on this port and allowed_vlans must be empty.",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text=(
                            "System default profile (seeded by migration) — permanently locked, "
                            "never deletable."
                        ),
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SwitchPortVlanProfileAllowedVlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="vlan",
            name="subnet",
            field=models.CharField(
                blank=True,
                help_text=(
                    "IPv4 subnet in CIDR notation, e.g. 10.200.0.0/21. Leave blank for an L2-only "
                    "VLAN with no tracked addressing (ADR 0012) — no gateway, DHCP range, rack "
                    "range, or static address may then be set on it."
                ),
                max_length=18,
                validators=[inventory.validators.validate_ipv4_cidr],
            ),
        ),
        migrations.AddConstraint(
            model_name="vlan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("subnet", ""), _negated=True),
                    models.Q(
                        ("default_gateway__isnull", True),
                        ("dhcp_range_start__isnull", True),
                        ("dhcp_range_end__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="vlan_subnetless_has_no_addressing",
            ),
        ),
        migrations.AddField(
            model_name="switchportvlanprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="switchportvlanprofile",
            name="native_vlan",
            field=models.ForeignKey(
                help_text=(
                    "Primary (untagged) VLAN — implicitly allowed, must not also appear in "
                    "allowed_vlans."
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.vlan",
            ),
        ),
        migrations.AddField(
            model_name="switchportvlanprofileallowedvlan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="switchportvlanprofileallowedvlan",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowed_vlan_links",
                to="inventory.switchportvlanprofile",
            ),
        ),
        migrations.AddField(
            model_name="switchportvlanprofileallowedvlan",
            name="vlan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.vlan",
            ),
        ),
        migrations.AddField(
            model_name="switchportvlanprofile",
            name="allowed_vlans",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Additional tagged VLANs, beyond the implied native VLAN. Must be empty if "
                    "all_vlans_allowed is set or port_mode is Access."
                ),
                related_name="+",
                through="inventory.SwitchPortVlanProfileAllowedVlan",
                to="inventory.vlan",
            ),
        ),
        migrations.AddConstraint(
            model_name="switchportvlanprofileallowedvlan",
            constraint=models.UniqueConstraint(fields=("profile", "vlan"), name="unique_profile_allowed_vlan"),
        ),
        migrations.AddConstraint(
            model_name="switchportvlanprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="switchportvlanprofile_name_not_blank"
            ),
        ),
        # Seed the system Default VLAN + Default profile — must run after
        # SwitchPortVlanProfile exists (immediately above) and before the
        # profile FK defaults below, whose callable default resolves this
        # seeded row at AddField-apply time (see default_switch_port_vlan_profile
        # in inventory/models.py) — Django computes a field's default once
        # to backfill existing rows even on an empty table, so the row must
        # already exist by then.
        migrations.RunPython(seed_defaults, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="networkswitchtypeport",
            name="profile",
            field=models.ForeignKey(
                default=inventory.models.default_switch_port_vlan_profile,
                help_text="Switch Port VLAN Profile — defaults to the system Default profile if none is selected.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="type_ports",
                to="inventory.switchportvlanprofile",
            ),
        ),
        migrations.AddField(
            model_name="networkswitchport",
            name="profile",
            field=models.ForeignKey(
                default=inventory.models.default_switch_port_vlan_profile,
                help_text="Switch Port VLAN Profile. Can be swapped for another unless a device is connected.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ports",
                to="inventory.switchportvlanprofile",
            ),
        ),
        # No semantic backfill from here on: every existing type port/port
        # (there shouldn't be any real ones — see the module comment above)
        # was just pointed at Default by the AddFields above, and its prior
        # port_mode/native_vlan/allowed_vlans are now discarded outright.
        migrations.RemoveConstraint(
            model_name="networkswitchportallowedvlan",
            name="unique_switch_port_allowed_vlan",
        ),
        migrations.RemoveField(
            model_name="networkswitchport",
            name="allowed_vlans",
        ),
        migrations.RemoveConstraint(
            model_name="networkswitchtypeportallowedvlan",
            name="unique_switch_type_port_allowed_vlan",
        ),
        migrations.RemoveField(
            model_name="networkswitchtypeport",
            name="allowed_vlans",
        ),
        migrations.RemoveField(
            model_name="networkswitchport",
            name="native_vlan",
        ),
        migrations.RemoveField(
            model_name="networkswitchport",
            name="port_mode",
        ),
        migrations.RemoveField(
            model_name="networkswitchtypeport",
            name="native_vlan",
        ),
        migrations.RemoveField(
            model_name="networkswitchtypeport",
            name="port_mode",
        ),
        migrations.RemoveField(
            model_name="networkswitchportallowedvlan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="networkswitchportallowedvlan",
            name="port",
        ),
        migrations.RemoveField(
            model_name="networkswitchportallowedvlan",
            name="vlan",
        ),
        migrations.RemoveField(
            model_name="networkswitchtypeportallowedvlan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="networkswitchtypeportallowedvlan",
            name="type_port",
        ),
        migrations.RemoveField(
            model_name="networkswitchtypeportallowedvlan",
            name="vlan",
        ),
        migrations.DeleteModel(
            name="NetworkSwitchPortAllowedVlan",
        ),
        migrations.DeleteModel(
            name="NetworkSwitchTypePortAllowedVlan",
        ),
    ]
