# Generated by Django 6.0.7 on 2026-07-26 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_switch_port_vlan_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="switchportvlanprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("port_mode", "access"), ("all_vlans_allowed", True), _negated=True),
                name="switchportvlanprofile_access_excludes_all_vlans_allowed",
            ),
        ),
    ]
