# Generated by Django 6.0.7 on 2026-07-27 00:30

import django.db.models.deletion
import inventory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_access_mode_excludes_all_vlans_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackvlanrange',
            name='address_range',
            field=models.CharField(blank=True, help_text="Leave blank to suggest the next free block sized for the rack's slot count.", max_length=18, validators=[inventory.validators.validate_ipv4_cidr]),
        ),
        migrations.AlterField(
            model_name='switchportvlanprofile',
            name='all_vlans_allowed',
            field=models.BooleanField(default=False, help_text='If set, every VLAN is allowed on this port and Allowed VLANs must be empty.'),
        ),
        migrations.AlterField(
            model_name='switchportvlanprofile',
            name='allowed_vlans',
            field=models.ManyToManyField(blank=True, help_text='Additional tagged VLANs, beyond the implied Native VLAN. Must be empty if Allow All VLANs is set or Port Mode is Access.', related_name='+', through='inventory.SwitchPortVlanProfileAllowedVlan', to='inventory.vlan'),
        ),
        migrations.AlterField(
            model_name='switchportvlanprofile',
            name='native_vlan',
            field=models.ForeignKey(help_text='Primary (untagged) VLAN — implicitly allowed, so it must not also be listed under Allowed VLANs.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vlan'),
        ),
        migrations.AlterField(
            model_name='switchportvlanprofile',
            name='port_mode',
            field=models.CharField(choices=[('trunk', 'Trunk'), ('access', 'Access')], default='trunk', help_text='Defaults to Trunk.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='subnet',
            field=models.CharField(blank=True, help_text='IPv4 subnet in CIDR notation, e.g. 10.200.0.0/21. Leave blank for an L2-only VLAN with no tracked addressing — no gateway, DHCP range, rack range, or static address may then be set on it.', max_length=18, validators=[inventory.validators.validate_ipv4_cidr]),
        ),
    ]
