# Generated by Django 6.0.7 on 2026-07-27 20:44, then hand-commented — see
# ADR 0014 and PLAN at we-had-discussed-rack-bright-thompson.md.
#
# Adds RackTemplate/RackTemplateVlan (a named, reusable VLAN set applied at
# rack creation) and, per ADR 0014 decision 9, finally bounds Rack.slot_count
# to >= 1 (a pre-existing gap the design deferred to this implementation).
#
# Destructive on the slot_count bound, same posture as ADR 0010's own
# migration: this project's local databases are rebuilt, not migrated over,
# so the AlterField/AddConstraint pair below assumes no existing Rack row has
# slot_count=0 rather than backfilling one. Verified against the dev
# database (na9000-mariadb-dev) before writing this migration: zero Rack rows
# exist there. If real production data with slot_count=0 ever exists before
# this runs, a staged backfill must be written first (same caveat ADR 0010
# makes for its own migration).
#
# No data migration and no seeding for RackTemplate — ADR 0014 decision 6:
# there is deliberately no system-seeded "Default" template.

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_help_text_operator_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slot_count', models.PositiveIntegerField(blank=True, help_text="Optional. Supplies the rack-creation form's slot count when left blank there — type a different value on that form to override it.", null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RackTemplateVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rack',
            name='slot_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.CheckConstraint(condition=models.Q(('slot_count__gte', 1)), name='rack_slot_count_gte_1'),
        ),
        migrations.AddField(
            model_name='racktemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racktemplatevlan',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racktemplatevlan',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_links', to='inventory.racktemplate'),
        ),
        migrations.AddField(
            model_name='racktemplatevlan',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rack_template_links', to='inventory.vlan'),
        ),
        migrations.AddField(
            model_name='racktemplate',
            name='vlans',
            field=models.ManyToManyField(blank=True, help_text='VLANs to allocate a rack address range for when a rack is created from this template. A VLAN with no subnet (L2-only, ADR 0012) cannot be included.', related_name='+', through='inventory.RackTemplateVlan', to='inventory.vlan'),
        ),
        migrations.AddConstraint(
            model_name='racktemplatevlan',
            constraint=models.UniqueConstraint(fields=('template', 'vlan'), name='unique_rack_template_vlan'),
        ),
        migrations.AddConstraint(
            model_name='racktemplate',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='racktemplate_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='racktemplate',
            constraint=models.CheckConstraint(condition=models.Q(('slot_count__isnull', True), ('slot_count__gte', 1), _connector='OR'), name='racktemplate_slot_count_gte_1'),
        ),
    ]
