# Generated by Django 6.0.7 on 2026-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rack_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdeviceport',
            name='slot_offset',
            field=models.PositiveIntegerField(default=0, help_text="Address offset from the device's slot, copied from the device's type — locked after creation. Above 0, this port's address is derived from the offset-0 port on the same VLAN and can't be edited directly."),
        ),
        migrations.AddField(
            model_name='networkdevicetypeport',
            name='slot_offset',
            field=models.PositiveIntegerField(default=0, help_text="Address offset from the device's slot. Leave at 0 unless the hardware itself derives this port's address from another port's (e.g. a console engine at control + 1)."),
        ),
    ]
