# Generated by Django 6.0.7 on 2026-08-02, then hand-edited — see ADR 0018 and
# PLAN-adr-0018.md.
#
# Destructive-database posture, same as every prior migration in this project
# (ADR 0010's own migration first said it, ADR 0012's 0006 repeats it): this
# project's local databases are rebuilt, not migrated over, so
# link_production_companions() below is the only "backfill" this migration
# does, and it is a real, idempotent linking pass over whatever rows already
# exist — not a destructive default assignment. An empty database (the usual
# case for this project) makes it a no-op.

import django.db.models.deletion
from django.db import migrations, models


def link_production_companions(apps, schema_editor):
    """Link the production DM7C/DM3 device-control-interface rows to their
    consoles (ADR 0018 decision 6), by the same ``-device-control`` hostname
    suffix convention the importer now also uses (``import_prod_data.py``'s
    companion pre-pass) — this migration predates that importer change, so
    existing production-shaped data (created before this decision existed)
    needs its two pairs linked after the fact.

    Matches case-insensitively, within one rack (decision 4): stripping the
    suffix from ``dm7c-1-device-control`` gives ``dm7c-1``, and its host row
    is spelled ``DM7C-1`` in production. Exact matching would find the DM3
    pair (same case) and silently miss the DM7C one — the whole point of a
    migration that's supposed to close this gap, not leave half of it open.

    For each unlinked ``-device-control``-suffixed row: exactly one
    case-insensitive stem match in the same rack links it (setting
    ``companion.host`` and the host's ``device_type.companion_type`` to the
    companion's own type); zero, several, or a host type already pointing at
    a *different* companion type is a loud ``RuntimeError`` naming the rack,
    slot and hostname, not a guess. Already-linked rows are skipped, so a
    re-run is idempotent, and an empty database is a no-op.

    Uses ``apps.get_model`` historical models throughout, which have no
    custom ``save()`` — so none of the live model's type-lock/companion
    validation runs here; this migration is the one place those invariants
    are established rather than checked.
    """
    NetworkDevice = apps.get_model("inventory", "NetworkDevice")

    suffix = "-device-control"
    candidates = list(
        NetworkDevice.objects.filter(hostname__iendswith=suffix, host__isnull=True).select_related(
            "device_type", "rack"
        )
    )
    for companion in candidates:
        stem = companion.hostname[: -len(suffix)]
        matches = list(
            NetworkDevice.objects.filter(rack_id=companion.rack_id, hostname__iexact=stem).exclude(
                pk=companion.pk
            )
        )
        if len(matches) != 1:
            raise RuntimeError(
                f"Cannot link companion {companion.hostname!r} (rack={companion.rack_id}, "
                f"slot={companion.rack_slot}): expected exactly one host row matching "
                f"hostname__iexact={stem!r} in the same rack, found {len(matches)} (ADR 0018)."
            )
        host = matches[0]
        host_type = host.device_type
        if host_type.companion_type_id is not None and host_type.companion_type_id != companion.device_type_id:
            raise RuntimeError(
                f"Cannot link companion {companion.hostname!r} to host {host.hostname!r} "
                f"(rack={companion.rack_id}, slot={companion.rack_slot}): {host_type} already "
                f"declares a different companion_type (id={host_type.companion_type_id}) than "
                f"{companion.device_type_id} (ADR 0018)."
            )
        if host_type.companion_type_id is None:
            host_type.companion_type_id = companion.device_type_id
            host_type.save(update_fields=["companion_type"])
        companion.host_id = host.pk
        companion.save(update_fields=["host"])


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_slot_offsets"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkdevicetype",
            name="companion_type",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The type this type's instances materialize as an inseparable companion "
                    "device at creation (ADR 0018) — e.g. a Yamaha DM7C's Device Control "
                    "Interface. Leave blank for an ordinary type with no companion."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companion_of",
                to="inventory.networkdevicetype",
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="host",
            field=models.OneToOneField(
                blank=True,
                help_text=(
                    "Set only for a companion device (ADR 0018) — the device this one cannot "
                    "exist without. Never set directly; a host materializes its own companion "
                    "at creation."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companion",
                to="inventory.networkdevice",
            ),
        ),
        migrations.RunPython(link_production_companions, reverse_code=migrations.RunPython.noop),
    ]
