# Generated by Django 6.0.7 on 2026-08-07 23:14, then hand-edited — see ADR
# 0021 and PLAN-adr-0021.md.
#
# Destructive-database posture, same as every prior migration in this
# project (ADR 0010's own migration first said it, 0011_device_companions
# repeats it): this project's local databases are rebuilt, not migrated
# over. Unlike 0011, this migration genuinely has nothing to backfill — no
# RunPython, no data migration. Every existing VLAN row is validly null on
# the new ``department`` column (ADR 0021 decision 2), and the ADR
# explicitly rejected backfilling by ``vlan_id`` range as baking one site's
# numbering into schema history permanently.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_device_companions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vlan',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional. The department that owns this VLAN, e.g. Audio, Lighting, Video.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlans', to='inventory.department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='department_name_not_blank'),
        ),
    ]
