# Generated by Django 6.0.7 on 2026-08-16 17:26, reordered by hand: Owner (with
# both its check constraints) first, then the ten AddFields, matching
# PLAN-hostname-ingredients.md's own description of this migration's shape.
#
# Every field is nullable or blank-able, so no data migration and no
# default — existing rows are untouched. ADR 0023 settles the whole scheme;
# this migration builds only the fields (phase 17), nothing that computes.

import django.db.models.deletion
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0015_add_in_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(help_text='Short, DNS-safe identifier used in hostnames, e.g. "mps".', max_length=63, unique=True, validators=[inventory.validators.validate_dns_label])),
                ('name', models.CharField(help_text='Full name, e.g. "MPS".', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='owner_slug_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='owner_name_not_blank'),
        ),
        migrations.AddField(
            model_name='rack',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Optional. Defaults a racked item's own Owner at creation (ADR 0023) — a suggestion, not inheritance; moving this rack to a different owner never touches equipment already in it.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='inventory.owner'),
        ),
        migrations.AddField(
            model_name='rack',
            name='location_slug',
            field=models.CharField(blank=True, help_text='Optional, DNS-safe location name used in hostnames, e.g. "wpcsrl". Blank means this rack contributes no location component — not that it\'s virtual: AVIO and SPARE both carry one, only CONSOLES doesn\'t (ADR 0023).', max_length=63, null=True, unique=True, validators=[inventory.validators.validate_dns_label]),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Hostname component 1 (ADR 0023) — defaults from this switch's rack at creation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='switches', to='inventory.owner'),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='hostname_purpose',
            field=models.CharField(blank=True, help_text='Hostname component 4, e.g. "sub" or "midhi-01-04" — a non-numeric qualifier belongs here, not in the sequence below (ADR 0023).', max_length=63, validators=[inventory.validators.validate_dns_label]),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='hostname_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Hostname component 5 — an integer distinguishing otherwise-identical names, e.g. 1 or 2 for mps-avio-aes-1 and mps-avio-aes-2 (ADR 0023).', null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Hostname component 1 (ADR 0023) — defaults from this device's rack at creation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.owner'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='hostname_purpose',
            field=models.CharField(blank=True, help_text='Hostname component 4, e.g. "sub" or "midhi-01-04" — a non-numeric qualifier belongs here, not in the sequence below (ADR 0023).', max_length=63, validators=[inventory.validators.validate_dns_label]),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='hostname_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Hostname component 5 — an integer distinguishing otherwise-identical names, e.g. 1 or 2 for mps-avio-aes-1 and mps-avio-aes-2 (ADR 0023).', null=True),
        ),
        migrations.AddField(
            model_name='networkswitchtype',
            name='hostname_slug',
            field=models.CharField(blank=True, help_text='Operator-set hostname abbreviation, e.g. "sg300-10mp". Never auto-filled — slugify("IK-42") gives "ik-42" where the name in use might be "ik42" — and deliberately not unique: two profiles of one model both carry the same abbreviation. Blank means this Type offers no computed hostnames (ADR 0023).', max_length=63, validators=[inventory.validators.validate_dns_label]),
        ),
        migrations.AddField(
            model_name='networkdevicetype',
            name='hostname_slug',
            field=models.CharField(blank=True, help_text='Operator-set hostname abbreviation, e.g. "ik42". Never auto-filled — slugify("IK-42") gives "ik-42" where the name in use might be "ik42" — and deliberately not unique: two profiles of one model both carry the same abbreviation. Blank means this Type offers no computed hostnames (ADR 0023).', max_length=63, validators=[inventory.validators.validate_dns_label]),
        ),
    ]
