# Generated by Django 6.0.7 on 2026-08-20 00:46

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_seed_hostname_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='dante_unit_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Yamaha consoles find and control this device by this number. Must be unique across every Yamaha-controlled device on the network — stage boxes and wireless receivers share one range. 1–127. Leave blank for equipment that is not controlled by a Yamaha console, including the consoles themselves.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(127)]),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.UniqueConstraint(fields=('dante_unit_id',), name='unique_device_dante_unit_id'),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.CheckConstraint(condition=models.Q(('dante_unit_id__isnull', True), ('dante_unit_id__range', (1, 127)), _connector='OR'), name='networkdevice_dante_unit_id_range'),
        ),
    ]
