# Generated by Django 6.0.7 on 2026-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_derived_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkdevicetypeport",
            name="slot_offset",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "Address offset from the device's own rack slot (ADR 0027) — every static "
                    "address is range_base + rack_slot + slot_offset. Leave at 0 unless this port "
                    "needs a second, distinct address on its VLAN (e.g. a console engine at "
                    "control + 1, or a second interface like a Yamaha console's Device Control)."
                ),
            ),
        ),
    ]
