# Generated by Django 6.0.7 on 2026-08-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_networkdevicetypeport_slot_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdeviceport',
            name='slot_offset',
            field=models.PositiveIntegerField(default=0, help_text="Address offset from the device's own rack slot, copied from the device's type — locked after creation. This port's address is range_base + rack_slot + slot_offset (ADR 0027) and can't be edited directly."),
        ),
    ]
