"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Off by default; opt into a local dev/test run explicitly via DJANGO_DEBUG=true.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# Must come from the environment outside DEBUG mode — a key baked into source
# would be public (and identical across every checkout) the moment it's committed.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"  # noqa: S105
    else:
        raise ImproperlyConfigured("SECRET_KEY environment variable must be set outside DJANGO_DEBUG=true.")

ALLOWED_HOSTS: list[str] = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "auditlog",
    "inventory",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Read-only UI (phase 15, ADR 0020) — Django's own defaults for these three
# are all wrong for this project. LOGIN_URL defaults to "/accounts/login/",
# which nothing routes without this; a bare @login_required view would send
# a logged-out visitor to a 404 rather than a login form. LOGIN_REDIRECT_URL
# defaults to "/accounts/profile/", equally unrouted. LOGOUT_REDIRECT_URL
# defaults to None, which would render Django's own "logged out" template —
# django.contrib.admin ships a registration/logged_out.html that would win
# over any override of ours (admin precedes inventory in INSTALLED_APPS), so
# pointing this at "/" instead sidesteps that template entirely rather than
# needing a project-level TEMPLATES["DIRS"] to shadow it (ADR 0020's plan,
# revision 2, decision 6 — one of the ADR's stated prerequisites is closed
# by not doing it).
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Same fail-closed pattern as SECRET_KEY: a missing DB_PASSWORD outside DEBUG
# mode should error loudly, not silently fall back to a dev-only credential
# on a misconfigured shared/staging box.
DB_PASSWORD = os.environ.get("DB_PASSWORD")
if not DB_PASSWORD:
    if DEBUG:
        DB_PASSWORD = "na9000dev"  # noqa: S105
    else:
        raise ImproperlyConfigured("DB_PASSWORD environment variable must be set outside DJANGO_DEBUG=true.")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "network_addresser_9000"),
        "USER": os.environ.get("DB_USER", "na9000"),
        "PASSWORD": DB_PASSWORD,
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# Give each git worktree its own test database.
#
# Worktrees share .env — it is symlinked from the main checkout via the
# worktree.symlinkDirectories setting — so every worktree resolves to the same
# DB_NAME. Without this, two test runs in parallel worktrees contend for the
# same test_<DB_NAME>, and --noinput lets whichever starts second silently
# destroy the first one's database mid-run.
#
# This is derived here rather than in the shell command deliberately: Claude
# Code's permission matcher refuses to match an allow rule against any command
# containing $(...) substitution, so a shell-derived name would prompt on every
# single test run. Only TEST.NAME is touched, so the runtime database is
# unaffected; the main checkout keeps Django's default test_<DB_NAME>.
if ".claude/worktrees/" in BASE_DIR.as_posix():
    _worktree_slug = re.sub(r"[^A-Za-z0-9]", "_", BASE_DIR.name)[:40]
    DATABASES["default"]["TEST"] = {"NAME": f"test_na9k_wt_{_worktree_slug}"[:64]}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves collected static files directly from the app container
# (ADR 0009) — no separate nginx/static service until external exposure
# requires a reverse proxy anyway. The manifest storage requires a
# `collectstatic` run to have produced staticfiles.json; local dev never
# runs collectstatic, so it falls back to the plain storage there instead of
# every {% static %} tag raising ValueError.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# Mutation audit trail (ADR 0004), via django-auditlog — see ADR 0008 and,
# for the port-profile models added in phase 8, ADR 0010.
#
# Scoped to ADR 0004's three named categories rather than every field on
# every object: address overrides and rack/slot reassignment get
# ``include_fields`` naming just the overridable/reassignable field(s);
# container/type models (nothing trivial-and-noisy on them) get full
# tracking; ``NetworkSwitchPort.description`` is explicitly excluded — it's
# the ADR's own "a typo fix to a port description doesn't need forensic
# tracking" example. Every model is still registered so removals (ADR 0007)
# are always logged, regardless of whether its edits are scoped.
#
# ``NetworkSwitchTypePort``/``NetworkDeviceTypePort`` (ADR 0010's port
# profile templates) get full tracking like the type models they belong
# to — a profile's port layout is exactly the kind of thing later
# instances depend on, not a trivial field. They're also only ever
# editable before their parent type has any instance (locked afterward),
# so there's no ongoing edit-noise to scope away here.
#
# ``created_at`` is added to every ``include_fields`` list below for a
# subtler reason: auditlog computes deletion diffs by comparing the row's
# real values against ``None`` defaults, so if every included field happens
# to already be ``None``/blank at delete time — a spare-pool switch/device
# (unracked: ``rack``/``rack_slot`` both null) or a DHCP device port
# (``address`` null) — the diff comes back empty and *no* deletion is
# logged at all, silently violating "removals are always logged."
# ``created_at`` is never null and never edited after creation, so it
# always registers a change on create/delete without ever contributing
# edit-noise on an ordinary update.
#
# ``NetworkDevicePort.default_gateway`` is a read-only property derived
# live from its VLAN (ADR 0010), not a stored column — it can't be (and
# isn't) named here; ``is_dhcp`` is tracked instead, since toggling a port
# between DHCP and static is itself an address-override-adjacent event.
#
# ``allowed_vlans`` is a ManyToManyField, which auditlog never diffs as an
# ordinary field (Django M2M changes don't even go through the model's own
# ``save()``) — it has to be named explicitly via ``m2m_fields`` to get
# change tracking at all.
#
# ``SwitchPortVlanProfile`` (phase 9, ADR 0012) gets full scalar + M2M
# tracking: unlike the seed-once ``*TypePort`` templates, a profile is
# referenced *live* by every port that uses it, so editing one is a
# fleet-wide config change squarely within ADR 0004's "mutations are
# logged, not just creation." ``NetworkSwitchTypePort``/``NetworkSwitchPort``
# no longer carry ``allowed_vlans`` themselves (that lives on the profile
# now) — the profile FK they do carry is an ordinary scalar field, already
# covered by their existing tracking below with no extra configuration.
#
# ``m2m_fields`` only tracks changes made *through the M2M manager*
# (``.add()``/``.set()``/``.remove()``, which fire ``m2m_changed``) —
# ``SwitchPortVlanProfileAllowedVlan`` supports direct row creation/deletion
# too (see its own ``clean()``/``save()``), which never fires that signal
# and so would otherwise leave a supported, config-changing write path
# completely unaudited. Registering the through model itself closes that
# gap with its own CREATE/DELETE log entries.
#
# ``NetworkDevice.host`` (ADR 0022 PR 3 — an add-in card's "currently fitted
# to" pointer) joins the include list below, but this alone is *necessary,
# not sufficient*: Django's deletion collector clears a ``SET_NULL`` reverse
# FK with ``QuerySet.update()``, which bypasses ``Model.save()`` and every
# auditlog signal, so orphaning a card by deleting its host would still
# leave no trace on the card's own history without
# ``inventory.models._clear_installed_cards_before_delete()`` (a
# ``pre_delete`` receiver) doing the clearing through an ordinary, audited
# ``save()`` per row first. Same reasoning for the admin's Pull action.
AUDITLOG_INCLUDE_TRACKING_MODELS = (
    "inventory.VLAN",
    # Bare, all fields tracked (ADR 0021) — VLAN is already registered bare
    # above, so its new `department` FK is covered with no entry change.
    "inventory.Department",
    # ADR 0023 — Owner, bare like Department: a descriptive vocabulary
    # table with no per-field scoping needed.
    "inventory.Owner",
    "inventory.Rack",
    "inventory.NetworkSwitchType",
    "inventory.NetworkDeviceType",
    "inventory.NetworkDeviceTypePort",
    "inventory.NetworkSwitchTypePort",
    {"model": "inventory.SwitchPortVlanProfile", "m2m_fields": ["allowed_vlans"]},
    {
        "model": "inventory.SwitchPortVlanProfileAllowedVlan",
        "include_fields": ["profile", "vlan", "created_at"],
    },
    {"model": "inventory.RackVlanRange", "include_fields": ["address_range", "created_at"]},
    # ADR 0023 — owner/hostname_purpose/hostname_sequence join the existing
    # scoped include_fields lists below; a whitelist doesn't pick up new
    # fields automatically (unlike Rack/the two Type models above, which
    # are registered bare).
    {
        "model": "inventory.NetworkSwitch",
        "include_fields": [
            "rack",
            "rack_slot",
            "owner",
            "hostname_purpose",
            "hostname_sequence",
            "created_at",
        ],
    },
    {"model": "inventory.NetworkSwitchAddress", "include_fields": ["address", "created_at"]},
    {"model": "inventory.NetworkSwitchPort", "exclude_fields": ["description"]},
    {
        "model": "inventory.NetworkDevice",
        "include_fields": [
            "rack",
            "rack_slot",
            "host",
            "owner",
            "hostname_purpose",
            "hostname_sequence",
            "created_at",
        ],
    },
    {
        "model": "inventory.NetworkDevicePort",
        "include_fields": ["address", "is_dhcp", "created_at"],
    },
    {"model": "inventory.RackTemplate", "m2m_fields": ["vlans"]},
    {
        "model": "inventory.RackTemplateVlan",
        "include_fields": ["template", "vlan", "created_at"],
    },
)
